# Generated by Django 5.0.4 on 2024-07-03 09:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_studentenrollment_enrollment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentenrollment',
            name='enrollment_date',
            field=models.DateField(default=datetime.datetime(2024, 7, 3, 9, 50, 0, 313357, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='studentenrollment',
            name='grade',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('F', 'F')], default='A', max_length=1),
        ),
    ]
