# Generated by Django 5.0.4 on 2024-07-03 09:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_alter_studentenrollment_enrollment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentenrollment',
            name='enrollment_date',
            field=models.DateField(default=datetime.datetime(2024, 7, 3, 9, 53, 12, 31835, tzinfo=datetime.timezone.utc)),
        ),
    ]
