# Generated by Django 5.0.4 on 2024-07-03 09:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_alter_studentenrollment_enrollment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturerprofile',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='studentenrollment',
            name='enrollment_date',
            field=models.DateField(default=datetime.datetime(2024, 7, 3, 9, 57, 1, 330636, tzinfo=datetime.timezone.utc)),
        ),
    ]
