# Generated by Django 5.0.4 on 2024-07-27 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='surface_type',
            field=models.CharField(choices=[('Clay', 'Clay'), ('Grass', 'Grass'), ('Hard Court', 'Hard Court'), ('Not Selected', 'Not Selected')], default='Not Selected', max_length=12),
        ),
    ]
