# Generated by Django 5.0.4 on 2024-07-07 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_zoodisplayanimal'),
    ]

    operations = [
        migrations.AddField(
            model_name='veterinarian',
            name='availability',
            field=models.BooleanField(default=False),
        ),
    ]
