# Generated by Django 5.0.4 on 2024-07-30 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='last_update',
            new_name='last_updated',
        ),
    ]
