# Generated by Django 5.0.4 on 2024-06-24 19:54

from django.db import migrations


def set_rarity(apps, schema_editor):
    item_model = apps.get_model('main_app', 'Item')

    item_object = item_model.objects.all()

    for item in item_object:
        if item.price <= 10:
            item.rarity = 'Rare'
        elif 11 <= item.price <= 20:
            item.rarity = 'Very Rare'
        elif 21 <= item.price <= 30:
            item.rarity = 'Extremely Rare'
        else:
            item.rarity = 'Mega Rare'

    item_model.objects.bulk_update(item_object, ['rarity'])


def reverse_set_rarity(apps, schema_editor):
    item_model = apps.get_model('main_app', 'Item')

    for i in item_model.objects.all():
        i.rarity = i._meta.get_field('rarity').default
        i.save()


class Migration(migrations.Migration):
    dependencies = [
        ('main_app', '0011_item'),
    ]

    operations = [
        migrations.RunPython(set_rarity, reverse_set_rarity)
    ]
