# Generated by Django 5.0.4 on 2024-06-24 21:11

from django.db import migrations


def set_new_price(apps, schema_editor):
    MULTIPLIER = 120

    smartphone = apps.get_model('main_app', 'Smartphone')

    smartphone_object = smartphone.objects.all()
    price_list = [p.price for p in smartphone_object]

    for p in smartphone_object:
        p.price = len(p.brand) * MULTIPLIER
    smartphone.objects.bulk_update(smartphone_object, ['price'])
    return price_list

def set_category(apps, schema_editor):
    smartphone = apps.get_model('main_app', 'Smartphone')
    smartphone_object = smartphone.objects.all()

    for p in smartphone_object:
        if p.price >= 750:
            p.category = 'Expensive'
        else:
            p.category = 'Cheap'
    smartphone.objects.bulk_update(smartphone_object, ['category'])


def order_of_performance(apps, schema_editor):
    set_new_price(apps, schema_editor)
    set_category(apps, schema_editor)


def reverse_info(apps, schema_editor):
    smartphone = apps.get_model('main_app', 'Smartphone')

    for i in smartphone.objects.all():
        i.category = i._meta.get_field('category').default
        i.save()

class Migration(migrations.Migration):
    dependencies = [
        ('main_app', '0013_smartphone'),
    ]

    operations = [
        migrations.RunPython(order_of_performance, reverse_info)
    ]
