# Generated by Django 5.0.4 on 2024-06-25 12:32

from django.db import migrations
from django.utils import timezone


def modify_delivery(apps, schema_editor):
    order = apps.get_model('main_app', 'Order')

    order_model = order.objects.all()

    for order in order_model:
        if order.status == 'Pending':
            order.delivery = order.order_date + timezone.timedelta(days=3)
            order.save()
        elif order.status == 'Completed':
            order.warranty = '24 months'
            order.save()
        elif order.status == 'Cancelled':
            order.delete()


def reverse_modify_delivery(apps, schema_editor):
    order_model = apps.get_model('main_app', 'Order')

    for order in order_model.objects.all():
        if order.status == 'Pending':
            order.delivery = None
        elif order.status == 'Completed':
            order.warranty = order_model._meta.get_field('warranty').default
        order.save()


class Migration(migrations.Migration):
    dependencies = [
        ('main_app', '0015_order'),
    ]

    operations = [
        migrations.RunPython(modify_delivery, reverse_modify_delivery)
    ]
