# Generated by Django 5.0.6 on 2024-06-18 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_weatherforecast'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherforecast',
            name='humidity',
            field=models.FloatField(default=None),
            preserve_default=False,
        ),
    ]
